### ISSUE TITLE
Unclear exception

### ISSUE THREAD

**Issue by riccardo** [ismb/jemma#197]
Reported by Roberto Pierpaoli on jemma ML:

2. [org.energy_home.jemma.ah.internal.zigbee.ZigBeeManagerImpl] : unable to save nullorg.energy_home.jemma.ah.zigbee.properties
java.net.MalformedURLException: no protocol: nullorg.energy_home.jemma.ah.zigbee.properties
at java.net.URL.<init>(URL.java:586)
at java.net.URL.<init>(URL.java:483)
at java.net.URL.<init>(URL.java:432)
at org.energy_home.jemma.ah.internal.zigbee.ZigBeeManagerImpl.saveProperties(ZigBeeManagerImpl.java:2251)
at org.energy_home.jemma.ah.internal.zigbee.ZigBeeManagerImpl.setUseNVM(ZigBeeManagerImpl.java:2110)
at org.energy_home.jemma.ah.internal.zigbee.ZigBeeManagerImpl.loadProperties(ZigBeeManagerImpl.java:2234)
at org.energy_home.jemma.ah.internal.zigbee.ZigBeeManagerImpl.handleBundleUpgrade(ZigBeeManagerImpl.java:351)
at org.energy_home.jemma.ah.internal.zigbee.ZigBeeManagerImpl.activate(ZigBeeManagerImpl.java:338)

**Comment by nport** [comment]
The exeption is not clear, but the problem is related to a missing property that tells to the ZigBee Network manager where to store persistently some status information. 
You need to start the JVM by adding the following properties (in the Eclipse Launch configuration Arguments (on Windows):

-Dosgi.instance.area=<url pointing to the local filesystem>
-Dorg.energy_home.jemma.m2m.device.configDir=<path on the local filesystem>

For instance (on Windows):

-Dosgi.instance.area=file:D:/Temp/data
-Dorg.energy_home.jemma.m2m.device.configDir=D:/temp/data
